service: funko-pop-addiction-enabler
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Query"
      Resource:
        - Fn::GetAtt: [FunkoTrackerSingleTable, Arn]

functions:
  getChaliceCollectiblesProducts:
    handler: chaliceCollectibles/handler.getChaliceCollectiblesProducts
    events:
      - http:
          path: challice/products
          method: get
          cors: true
  getFunkoDetailsByIdAndFandom:
    handler: dynamo/getFunkoDetailsByIdAndFandom.handler
    events:
      - http:
          path: fandom/{fandom_id}/funkos/{funko_id}/details
          method: get
          cors: true
  listFunkosByFandom:
    handler: dynamo/listFunkosByFandom.handler
    events:
      - http:
          path: fandom/{fandom_id}/funkos
          method: get
          cors: true
  searchFunkosByFandomAndFunkoName:
    handler: dynamo/searchFunkosByFandomAndFunkoName.handler
    events:
      - http:
          path: fandom/{fandom_id}/funkos/search
          method: get
          cors: true

resources:
  Resources:
    FunkoTrackerSingleTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
        BillingMode: PAY_PER_REQUEST
        TableName: funko-tracker-single-table
plugins:
  - serverless-finch

custom:
  client:
    bucketName: funko-pop-addiction-enabler-bucket
    distributionFolder: client/build
    errorDocument: index.html

package:
  exclude:
    - 'client/**'
    - 'tests/**'